# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - blog.md

footer: 'rss'

style: hacker # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
